= JMS basics
:source-highlighter: coderay

[source,java]
.get a jms context
----
  @Inject
  @JMSConnectionFactory("java:/ConnectionFactory")
  JMSContext context;
----

[source,java]
//TODO: look how jndi name should look like on jboss
.get a queue
----
  @Resource(lookup = "java:global/jms/queueName")
  Queue myQueue;
----

[source,java]
.Declare an async listener for incomming messages
----
@MessageDriven(name = "HelloWorldQueueMDB", activationConfig = {
    @ActivationConfigProperty(propertyName = "destinationLookup", propertyValue = "java:global/jms/queueName"),
    @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue"),
    @ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge")})
public class AsyncConsumer implements MessageListener {

  private static final Logger LOGGER = Logger.getLogger(AsyncConsumer.class.toString());

  public void onMessage(Message recivedMessage) {
    //Do something
  }
}
----

[source,java]
.Declare an async listener for incoming messages when injecting a context
----
 @Inject
 @JMSConnectionFactory("java:jboss/exported/jms/RemoteConnectionFactory")
 @JMSPasswordCredential(userName = "jms", password = "jms")
 JMSContext context;
----

[source,java]
.Authenticate on a MessageListener. Pass properties user and password.
----
@MessageDriven(activationConfig = {
    @ActivationConfigProperty(propertyName = "destinationLookup", propertyValue = "java:global/jms/pointsQueue"),
    @ActivationConfigProperty(propertyName = "connectionFactoryLookup", propertyValue = "java:jboss/exported/jms/RemoteConnectionFactory"),
    @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue"),
    @ActivationConfigProperty(propertyName = "user", propertyValue = "jms"),
        @ActivationConfigProperty(propertyName = "password", propertyValue = "jms"),
        @ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge")
})
----

[NOTE]
====
https://developer.jboss.org/thread/266416

In that case you would need to re-configure the relevant connector to point to the proper interface.  Here's how the configuration works:

    JMS client looks up and uses a particular connection factory, e.g. "jms/RemoteConnectionFactory".
    Said connection factory is configured to use a particular connector, e.g. "netty".
    The connector is configured with a particular socket-binding, e.g. "messaging".
    The socket-binding is configured to use a particular interface, e.g. "public".
    The interface is configured to listen on a particular inet-address, e.g. 0.0.0.0 in your case.
====


== Jboss specific
.Configuration on standalone-full.xml
[source,xml]
----
<subsystem xmlns="urn:jboss:domain:messaging-activemq:7.0">
            <server name="default">
                <statistics enabled="${wildfly.messaging-activemq.statistics-enabled:${wildfly.statistics-enabled:false}}"/>
                <security-setting name="#">
                    <role name="guest" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
                </security-setting>
                <address-setting name="#" dead-letter-address="jms.queue.DLQ" expiry-address="jms.queue.ExpiryQueue" max-size-bytes="10485760" page-size-bytes="2097152" message-counter-history-day-limit="10"/>
                <http-connector name="http-connector" socket-binding="http" endpoint="http-acceptor"/>
                <http-connector name="http-connector-throughput" socket-binding="http" endpoint="http-acceptor-throughput">
                    <param name="batch-delay" value="50"/>
                </http-connector>
                <in-vm-connector name="in-vm" server-id="0">
                    <param name="buffer-pooling" value="false"/>
                </in-vm-connector>
                <http-acceptor name="http-acceptor" http-listener="default"/>
                <http-acceptor name="http-acceptor-throughput" http-listener="default">
                    <param name="batch-delay" value="50"/>
                    <param name="direct-deliver" value="false"/>
                </http-acceptor>
                <in-vm-acceptor name="in-vm" server-id="0">
                    <param name="buffer-pooling" value="false"/>
                </in-vm-acceptor>
                <jms-queue name="ExpiryQueue" entries="java:/jms/queue/ExpiryQueue"/>
                <jms-queue name="DLQ" entries="java:/jms/queue/DLQ"/>
                <connection-factory name="InVmConnectionFactory" entries="java:/ConnectionFactory" connectors="in-vm"/>
                <connection-factory name="RemoteConnectionFactory" entries="java:jboss/exported/jms/RemoteConnectionFactory" connectors="http-connector"/>
                <pooled-connection-factory name="activemq-ra" entries="java:/JmsXA java:jboss/DefaultJMSConnectionFactory" connectors="in-vm" transaction="xa"/>
            </server>
        </subsystem>
----

The role element defines the rule a user must have.
.Configuration of allowd user roles
[source,xml]
----
<role name="guest" send="true" consume="true" create-non-durable-queue="true" delete-non-durable-queue="true"/>
----
Per default, when using java:jboss/exported/jms/RemoteConnectionFactory, the ApplicationRealm security realm is used. Actually is taken from the http-connector:
[source,xml]
----
<subsystem xmlns="urn:jboss:domain:messaging-activemq:7.0">
........
    <connection-factory name="RemoteConnectionFactory" entries="java:jboss/exported/jms/RemoteConnectionFactory" connectors="http-connector"/>
    <http-connector name="http-connector" socket-binding="http" endpoint="http-acceptor"/>
........
</subsystem>
----

[source,xml]
----
<subsystem xmlns="urn:jboss:domain:remoting:4.0">
    <http-connector name="http-remoting-connector" connector-ref="default" security-realm="ApplicationRealm"/>
</subsystem>
----

----


    Both type of connectors are used for establishing remote connection. Why is there a need to have both ?

The "http" acceptor/connector pair supports establishing connections over HTTP (as the name suggests).  These connections are then upgraded to "normal" TCP connections using the Artemis core protocol.  This upgrade functionality allows the application server to listen to just a single port (i.e. the HTTP port) and service lots of different kinds of protocols and connections.  The "remote" acceptor/connection pair doesn't support this HTTP upgrade functionality.



    Can I just use http-connector?

Depending on your use-case, yes.



    What are the scenarios that I have to use remote-connector instead of http-connector?

You'd a "remote" acceptor or connector if you were either accepting connections from to establishing a connection to a server that didn't support the HTTP upgrade functionality provided by the "http" acceptor/connector pair.  For example, if you were connecting to a standalone instance of Artemis you'd use a remote-connector or if you were accepting a connection from a legacy HornetQ client you'd use a remote-acceptor.
----